site_name: Stracquadanio Lab Documentation
nav:
        - "Home": "index.md"
        - "Systems setup":
                  - "GitHub": "./systems-setup/github.md"
                  - "Workstations": "./systems-setup/workstation.md"
                  - "Cell HPC": "./systems-setup/hpc-cell.md"

        - "Project Management":
                  - "Project lifecycle": "./projects-management/project-lifecycle.md"
                  - "Project workflows": "./projects-management/project-workflow.md"
                  - "Project workspaces": "./projects-management/project-workspace.md"

        - "Programming":
                  - "Coding standards": "./programming/coding-standards.md"
                #   - "Docker": "./programming/docker.md"
theme:
        name: readthedocs
        # palette:
        #     primary: blue grey

        highlightjs: true
        hljs_languages:
                - yaml
                - python
                - r
                - bash
extra_javascript:
   - 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'
   
markdown_extensions:
        - tables
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_div_format

